# https://github.com/golangci/golangci/wiki/Configuration

service:
  project-path: github.com/ullaakut/cameradar
  prepare:
    - apt-get update && apt-get install -y libcurl4-gnutls-dev
    - dep ensure
