cameradar:
  build: .
  dockerfile: Dockerfile
  env_file: env_file
  volumes:
    - "./conf:/tmp/conf:ro"
    - "./cameradar_thumbnails:/tmp/cameradar_thumbnails"
  links:
   - mysql
mysql:
  image: mysql:5.7
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: cmrdr
  ports:
   - "3306:3306"
